package com.example.chapter09.mimocode;

import java.io.IOException;
import java.time.Instant;
import java.util.List;

/**
 * 真实 MiMo-Code 会让 checkpoint-writer 子 Agent 总结上下文。这个示例
 * 用规则实现同一件事：从 history 中提取目标、动作、风险和下一步，
 * 再写入 session checkpoint。
 */
public final class CheckpointWriter {
    private final MarkdownMemoryStore memoryStore;

    public CheckpointWriter(MarkdownMemoryStore memoryStore) {
        this.memoryStore = memoryStore;
    }

    public String write(String sessionId, List<HistoryEvent> events) throws IOException {
        StringBuilder markdown = new StringBuilder();
        markdown.append("# Session checkpoint\n\n");
        markdown.append("- session: `").append(sessionId).append("`\n");
        markdown.append("- updated_at: `").append(Instant.now()).append("`\n\n");
        markdown.append("## Current goal\n");
        markdown.append("- Explain MiMo-Code memory/checkpoint/history mechanics and map them to Java examples.\n\n");

        markdown.append("## Recent evidence\n");
        events.stream()
                .skip(Math.max(0, events.size() - 6))
                .forEach(event -> markdown.append("- [")
                        .append(event.kind())
                        .append("] ")
                        .append(event.title())
                        .append(": ")
                        .append(event.body())
                        .append("\n"));

        markdown.append("\n## Open risks\n");
        markdown.append("- Memory generated by LLM must be checked against raw history before promotion.\n");
        markdown.append("- Too many tiny docs create navigation overhead; merge when a page has no standalone example.\n\n");
        markdown.append("## Next step\n");
        markdown.append("- Keep theory pages connected to runnable Java demos and diagrams.\n");

        memoryStore.writeSessionCheckpoint(sessionId, markdown.toString());
        return markdown.toString();
    }
}
