FROM eclipse-temurin:21-jre

WORKDIR /app

COPY target/enterprise-ops-agent-0.0.1-SNAPSHOT.jar app.jar

ENV SERVER_PORT=8080
ENV AI_PROVIDER=deepseek

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
